__kernel void fill(__global float *res_g)
{
    int gid = get_global_id(0);

    res_g[gid] = 1.0;
}

__kernel void copy(__global float *src, __global float *dest)
{
    int gid = get_global_id(0);

    dest[gid] = src[gid];
}

__kernel void psum_step(__global float *src, __global float *dest, int stride)
{
    int gid = get_global_id(0);

    if(gid - stride >= 0)
        dest[gid] = src[gid] + src[gid - stride];
    else
        dest[gid] = src[gid];
}